# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: bedard.splitter::lang.campaigns.model

# Model Form Field configuration
form: $/bedard/splitter/models/campaign/fields.yaml

# Model Class name
modelClass: Bedard\Splitter\Models\Campaign

# Default redirect location
defaultRedirect: bedard/splitter/campaigns

# Create page
create:
    title: backend::lang.relation.create_name
    redirect: bedard/splitter/campaigns/update/:id
    redirectClose: bedard/splitter/campaigns

# Update page
update:
    title: backend::lang.relation.update_name
    redirect: bedard/splitter/campaigns
    redirectClose: bedard/splitter/campaigns

# Preview page
preview:
    title: backend::lang.relation.preview_name
